import { StyleSheet } from 'react-native'
import { getStatusBarHeight } from 'react-native-status-bar-height'
import { theme } from './core/theme'

const styles = {
  backButton: StyleSheet.create({
    container: {
      backgroundColor: 'red',
      //  width: 50, // Adjust the width as needed
      // height: 50,
    },
    /* image: {
      width: '100%',
      height: '100%',
      resizeMode: 'contain',
    },*/
  }),

  unlockedActionScreen: StyleSheet.create({
    container: {
      justifyContent: 'center',
      alignItems: 'center',
      flex: 1,
    },
    box: {
      alignItems: 'center',
      borderRadius: 6,
      backgroundColor: '#f4f4f4',
      borderStyle: 'solid',
      borderColor: 'black',
      borderWidth: 0.5,
      // flex: 1,
      width: '100%',
      justifyContent: 'center',
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 32,
      gap: 16,
      alignSelf: 'center',
      flexDirection: 'column',
    },

    buttonsContainer: {
      flexDirection: 'row',
      width: '100%',
      paddingHorizontal: 16,
      paddingVertical: 4,
      gap: 16,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      flex: 1,
    },
    buttonLater: {
      flex: 1,
      borderRadius: 6,
      backgroundColor: 'white',
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
      paddingVertical: 10,
      borderColor: '#000',
      borderWidth: 1,
      borderStyle: 'solid',
    },
    buttonAction: {
      flex: 1,
      borderRadius: 6,
      backgroundColor: 'black',
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
      paddingVertical: 10,
      borderColor: '#000',
      borderWidth: 1,
      borderStyle: 'solid',
    },
    buttonLaterText: {
      color: 'black',
      fontWeight: '500',
      fontSize: 16,
      lineHeight: 22,
      textAlign: 'center',
    },

    buttonActionText: {
      color: 'white',
      fontWeight: '500',
      fontSize: 16,
      lineHeight: 22,
      textAlign: 'center',
    },
    text1: {
      alignSelf: 'stretch',
      fontSize: 25,
      lineHeight: 22,
      fontWeight: '600',
      //fontFamily: FontFamily.poppinsSemiBold,
      color: '#000',
      textAlign: 'center',
    },

    text2: {
      alignSelf: 'stretch',
      color: '#000',
      fontWeight: '500',
      fontSize: 16,
      lineHeight: 22,
      textAlign: 'center',
    },
    icon: {
      //flex: 1,
      width: '100%',
      height: 80,
      //overflow: 'hidden',
      //alignItems: 'center',
      //justifyContent: 'center',
      textAlign: 'center',
    },
  }),

  revisionsScreen: StyleSheet.create({
    topNav: {
      justifyContent: 'center',
      flexDirection: 'row',
      alignItems: 'center',
      position: 'relative',
      justifyContent: 'space-between',
    },
    header: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    box: {
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 6,
      height: 84,
      width: '100%',
      //opacity: 0.35,
      paddingTop: 8,
      paddingBottom: 8,
      paddingLeft: 8,
      paddingRight: 8,
      marginVertical: 8,
      //backgroundColor: '#CECECE33',
      borderColor: '#cecece',
      backgroundColor: 'rgba(206, 206, 206, 0.2)',
      justifyContent: 'center',
      alignItems: 'center',
    },

    question: {
      textAlign: 'center',
      width: '100%',
      marginBottom: 16,
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '500',
      //fontFamily: FontFamily.sFProDisplay,
      color: 'black',
      width: 358,
    },
    title1: {
      fontSize: 17,
      letterSpacing: 0.2,
      alignSelf: 'stretch',
      textAlign: 'center',
      //fontFamily: FontFamily.poppinsLight,
      fontWeight: '300',
      lineHeight: 25,
      color: 'black',
      width: '100%',
    },
    title2: {
      fontSize: 10,
      letterSpacing: 0.1,
      textAlign: 'center',
      color: 'black',
      width: '100%',
      lineHeight: 25,
      fontWeight: '300',
    },
  }),

  background: StyleSheet.create({
    background: {
      flex: 1,
      width: '100%',
      backgroundColor: theme.colors.surface,
    },
    container: {
      flex: 1,
      // padding: 0,
      // paddingHorizontal: 5,
      paddingVertical: 18,
      width: 390,
      height: 262,
      top: 0,
      // gap: 13,
      // width: '100%',
      // height: 'auto',
      // gap: 13,
      maxWidth: 340,
      alignSelf: 'center',
    },
  }),
  button: StyleSheet.create({
    button: {
      width: '100%',
      marginVertical: 10,
      paddingVertical: 2,
    },
    text: {
      fontFamily: 'Poppins',
      fontWeight: '500',
      fontSize: 16,
      lineHeight: 22,
      textTransform: 'none',
    },
  }),
  bottomNavigationBar: StyleSheet.create({
    container: {
      position: 'relative',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: 'white',
      borderTopWidth: 1,
      borderTopColor: 'lightgray',
      width: '100%',
      marginBottom: 5,
    },
    tabBar: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingVertical: 10,
      width: '100%',
    },
    tabButton: {
      alignItems: 'center',
      paddingTop: 10,
    },
    icon: {
      width: 30,
      height: 30,
    },
    indicatorContainer: {
      position: 'absolute',
      bottom: 3,
      width: 10,
      height: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    indicator: {
      width: 5,
      height: 5,
      backgroundColor: '#62ff90',
      borderRadius: 10,
    },
    fixedRedBar: {
      position: 'absolute',
      bottom: 5,
      height: 5,
      width: 5,
      backgroundColor: '#ff4252',
      borderRadius: 10,
    },
  }),
  dashboard: StyleSheet.create({
    image: {
      borderRadius: '6px',
      display: 'flex',
      width: 24,
      height: 25,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 6,
      // marginLeft: 10,
    },
    imageContainer: {
      height: '100%',
      width: '25%',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 6,
      // backgroundColor: '#0000000d',
    },
    container: {
      width: '100%',
      justifyContent: 'center',
      padding: 1,
      alignItems: 'center',
      marginTop: 'auto',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 15,
    },
    userInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      width: 250,
      maxWidth: 300,
    },
    userPic: {
      width: 35,
      height: 35,
      borderRadius: 20,
    },
    userDetails: {
      marginLeft: 10,
      maxWidth: 180,
    },
    userName: {
      fontSize: 16,
      fontWeight: 'bold',
    },
    userLevel: {
      fontSize: 11,
      color: '#666',
    },
    progressBarContainer: {
      width: 100,
      height: 4,
      backgroundColor: '#ddd',
      borderRadius: 2,
      marginTop: 3,
    },
    progressBarFill: {
      width: '50%',
      height: '100%',
      backgroundColor: '#4caf50',
      borderRadius: 2,
    },
    streak: {
      fontSize: 18,
      fontWeight: 'bold',
    },
    dashboardContainer: {
      alignItems: 'center',
      justifyContent: 'space-around',
      width: '100%',
      paddingHorizontal: 12,
    },
    dailyChallengeBox: {
      borderWidth: 1,
      borderColor: '#ddd',
      padding: 0,
      borderRadius: 8,
      backgroundColor: 'white',
      marginBottom: 20,
      alignSelf: 'stretch',
      maxWidth: 340,
    },
    sectionTitle1: {
      fontSize: 10,
      marginBottom: 8,
      fontWeight: 'bold',
    },
    headerImage: {
      marginBottom: 8,
      width: 100,
      height: 15,
      padding: 2,
      marginRight: 2,
      alignItems: 'flex-start',
      marginTop: 4,
    },
    textContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 10,
    },
    iconContainer1: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#e8e8e8',
      padding: 0,
      height: 23,
      borderRadius: 6,
      marginBottom: 4,
      marginVertical: 0,
      alignSelf: 'flex-start',
    },

    textInfo: {
      flexDirection: 'column',
    },

    sectionTitle: {
      fontSize: 14,
      marginBottom: 8,
      fontWeight: 'bold',
    },
    greyBox: {
      backgroundColor: '#f5f5f5',
      padding: 0,
      borderRadius: 2,
      marginBottom: 2,
      alignItems: 'flex-start',
      height: 100,
    },
    challengeCategory: {
      marginTop: 6,
      fontSize: 14,
      color: 'black',
    },
    numOfQuestions: {
      fontSize: 14,
      color: 'black',
      marginBottom: 8,
      fontWeight: 'bold',
    },
    startButton: {
      backgroundColor: '#000',
      borderRadius: 8,
      paddingHorizontal: 20,
      paddingVertical: 10,
      marginLeft: 1,
    },
    startButtonText: {
      color: '#fff',
      fontSize: 14,
    },
    incompleteAction: {
      marginBottom: 20,
      alignSelf: 'stretch',
      maxWidth: 340,
    },
    blackBox: {
      borderWidth: 1,
      borderColor: '#ababab',
      borderRadius: 8,
      padding: 0,
      backgroundColor: 'transparent',
    },
    iconContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#f5f5f5',
      padding: 8,
      borderRadius: 6,
      marginBottom: 8,
      marginVertical: 0,
      paddingTop: 3,
      alignSelf: 'flex-start',
    },
    icon: {
      width: 20,
      height: 20,
      marginRight: 5,
    },
    almostGoneText: {
      color: '#000',
      fontSize: 11,
      fontWeight: 'bold',
    },
    bottomContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    unplugText: {
      color: '#000',
      fontSize: 14,
      marginLeft: 6,
    },
    claimButton: {
      borderWidth: 1,
      borderColor: '#000',
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderRadius: 2,
      margin: 8,
      backgroundColor: 'transparent',
    },
    claimButtonText: {
      color: '#000',
      fontSize: 15,
      fontWeight: 'bold',
    },
    availableIncentives: {
      marginBottom: 20,
      alignSelf: 'stretch',
      maxWidth: 340,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    seeAll: {
      color: '#000',
      fontSize: 14,
    },
    incentivesContainer: {
      flexDirection: 'row',
      marginTop: 6,
    },
    incentiveCard: {
      width: 70,
      height: 70,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#e8e8e8',
      borderRadius: 8,
      marginRight: 10,
    },
    incentiveImage: {
      width: 60,
      height: 60,
      borderRadius: 8,
      backgroundColor: '#f5f5f5',
    },
    revision: {
      marginBottom: 15,
      alignSelf: 'stretch',
      maxWidth: 340,
    },
    revisionContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      borderWidth: 0,
      borderColor: 'white',
      padding: 0,
      borderRadius: 1,
      // backgroundColor: 'white',
      alignItems: 'center',
    },
    revisionText: {
      fontSize: 11,
      color: '#666',
      textAlign: 'justify',
      flex: 1,
      marginRight: 10,
      marginTop: 6,
      marginBottom: 8,
    },
    roundButton: {
      backgroundColor: '#000',
      borderRadius: 10,
      paddingHorizontal: 7,
      paddingVertical: 6,
      marginLeft: 2,
      paddingTop: 3,
    },
    roundButtonText: {
      color: '#fff',
      fontSize: 11,
    },
  }),
  editProfileScreen: StyleSheet.create({
    headerContainer: {
      display: 'flex',
      width: '100%',
      justifyContent: 'start',
      alignItems: 'start',
      gap: '8px',
      flexDirection: 'row',
    },
    header: {
      color: theme.colors.greet,
      fontSize: 16,
      fontStyle: 'normal',
      fontWeight: 'bold',
      fontweight: 510,
      lineheight: 22,
    },
    container: {
      flex: 1,
      paddingHorizontal: 16,
      //justifyContent: 'center',
    },
    footer: {
      width: '100%',
      paddingHorizontal: 16,
      paddingBottom: 20,
    },
    saveButton: {
      borderRadius: 8,
      width: '100%',
      color: '#FFF',
      fontFamily: theme.colors.greet,
      fontSize: 16,
      fontStyle: 'normal',
      fontWeight: 500,
    },
  }),
  emailSignUp: StyleSheet.create({
    button: {
      backgroundColor: 'black',
      marginTop: 24,
    },
    row: {
      flexDirection: 'row',
      marginTop: 4,
    },
    link: {
      fontWeight: 'bold',
      color: theme.colors.primary,
    },
    checkboxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
    },
  }),

  header: StyleSheet.create({
    header: {
      fontSize: 21,
      color: theme.colors.greet,
      fontWeight: 'bold',
      // paddingVertical: 12,
      //width: '139.47',
      height: 'auto',
      //padding: 32,
      //paddingTop: 32,
      //paddingBottom: 32,
      //paddingHorizontal: 20,
      // gap: 8,
      //alignSelf: 'center',
      //alignItems: 'center',
      //justifyContent: 'center',
      textAlign: 'center',
    },
  }),
  incentiveDetailPage: StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: 'white',
    },
    container: {
      // paddingTop: 20,
    },
    headerTitle: {
      // height: 10 + getStatusBarHeight(),
      color: '#000',
      fontFamily: 'Poppins',
      font: 'normal',
      fontWeight: 400,
      paddingTop: '8px',
      alignContent: 'center',
      alignSelf: 'center',
      // textAlign:
      paddingLeft: '30px',
      fontSize: '18px',
    },
    backButton: {
      width: '24px',
      height: '24px',
      position: 'absolute',
      left: '16px',
      top: '7px',
    },
    headerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      width: '100%',
      zIndex: 1,
      paddingHorizontal: 16,
    },
    title: {
      color: '#000',
      style: 'normal',
      fontFamily: 'Poppins',
      fontSize: 18,
      fontWeight: '500',
      lineHeight: 22,
      // marginBottom: 16,
      // width: 187,
    },
    descriptionContainer: {
      display: 'flex',
      width: '100%',
      padding: '8px 16px',
      paddingTop: '20px',
      flexDirection: 'column',
      alignItems: 'flex-start',
    },
    heading: {
      fontFamily: 'SFProText-Regular',
      fontSize: 16,
      fontWeight: '600',
      lineHeight: 22,
      letterSpacing: 0.01,
      color: '#000000',
      marginBottom: 8,
    },
    content: {
      fontFamily: 'SFProText-Regular',
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 22,
      letterSpacing: 0.01,
      color: '#000000',
      marginBottom: 16,
    },
  }),
  incentivesList: StyleSheet.create({
    // safeArea: {
    //   flex: 1,
    //   height: '100%',
    //   width: '100%'
    // },
    //   headerContainer: {
    //     // flexDirection: 'row',
    //     alignItems: 'center',
    //     // justifyContent: 'flex-start',
    //     width: '100%',
    //   },
    headerTitle: {
      // height: 10 + getStatusBarHeight(),
      color: '#000',
      fontFamily: 'Poppins',
      font: 'normal',
      fontWeight: 400,
      paddingTop: '8px',
      // textAlign:
      paddingLeft: '130px',
      fontSize: '18px',
    },
    backButton: {
      width: '24px',
      height: '24px',
      position: 'absolute',
      left: '16px',
      top: '7px',
    },
    headerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      width: '100%',
      zIndex: 1,
      paddingHorizontal: 16,
    },
    listFrame: {
      display: 'flex',
      width: '100%',
      padding: '16px 8px',
      flexDirection: 'column',
      // gap: '8px',
      height: '100%' - getStatusBarHeight(),
      marginTop: 35 + getStatusBarHeight(),
    },
    //   headerTitle: {
    //     marginLeft: 36,
    //   },
    card: {
      flexDirection: 'row',
      alignItems: 'center',
      // // backgroundColor: '#0000000D',
      // borderRadius: 6,
      // borderWidth: 0.5,
      // borderColor: '#0000001A',
      width: '100%',
      minHeight: '80px',
      maxHeight: '20%',
      marginVertical: '2%',
      marginHorizontal: '0%',
      // justifyContent: 'space-between',
      borderRadius: 6,
      border: '0.5px solid rgba(0, 0, 0, 0.10)',
    },
    image: {
      borderRadius: '6px',
      display: 'flex',
      width: 24,
      height: 25,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 6,
      // marginLeft: 10,
    },
    imageContainer: {
      height: '100%',
      width: '25%',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 6,
      backgroundColor: '#0000000d',
    },
    textContainer: {
      // flex: 1,
      paddingHorizontal: 8,
      // justifyContent: 'center',
    },
    title: {
      // fontFamily: 'SFProDisplay-Regular',
      // fontSize: 18,
      // fontWeight: '500',
      // lineHeight: 24,
      textAlign: 'left',
      // alignSelf: 'stretch',
      color: '#000000',
      fontFamily: 'SF Pro Display',
      fontSize: '18px',
      fontWeight: '500',
      fontStyle: 'normal',
      // lineHeight: '24px', /* 133.333% */
    },
    subtitle: {
      alignSelf: 'stretch',
      fontFamily: 'SF Pro Text',
      fontSize: 12,
      fontWeight: '400',
      fontStyle: 'normal',
      lineHeight: 16,
      color: '#000000b3',
      // textAlign: 'left',
    },
  }),
  incorrectQuestionScreen: StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
  }),
  incorrectQuiz: StyleSheet.create({
    button: {
      backgroundColor: 'black',
    },
    AnswerBox: {
      width: 361,
      height: 214,
      borderWidth: 3,
      borderRadius: 6,
      borderColor: 'rgba(0, 0, 0, 0.05)',
      backgroundColor: 'rgba(0, 0, 0, 0.05)',
      alignItems: 'center',
      justifyContent: 'center',
    },

    answerText: {
      textAlign: 'center',
      fontSize: 24,
    },
    question: {
      marginBottom: 10,
      fontSize: 18,
    },
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    correctBox: {
      borderColor: 'rgba(19, 212, 2, 1)',
    },
    wrongBox: {
      borderColor: 'rgba(241, 58, 0, 1)',
    },
    progressBarContainer: {
      width: '100%',
      height: 20,
      marginBottom: 30,
    },

    correctMessage: {
      color: 'rgba(98, 218, 103, 1)',
      fontSize: 24,
      textAlign: 'center',
      marginBottom: 30,
    },
    wrongMessage: {
      color: 'rgba(255, 72, 15, 1)',
      fontSize: 24,
      textAlign: 'center',
      marginBottom: 20,
    },
    customMessage: {
      color: 'black',
      fontSize: 16,
      position: 'absolute',
      top: 390,
      width: '100%',
      textAlign: 'left',
    },
    disabledButton: {
      backgroundColor: 'black',
    },
    disabledButtonText: {
      color: 'white',
    },
  }),
  loadScreen: StyleSheet.create({
    container: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: [{ translateX: -48 }, { translateY: -4 }],
      flexDirection: 'row',
      width: 96,
      height: 8,
      justifyContent: 'space-between',
    },
    dot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: 'lightgrey',
    },
  }),
  loginFacebook: StyleSheet.create({
    forgotPassword: {
      width: '100%',
      alignItems: 'flex-end',
      marginBottom: 24,
    },
    row: {
      flexDirection: 'row',
      marginTop: 4,
    },
    forgot: {
      fontSize: 13,
      color: theme.colors.secondary,
    },
    link: {
      fontWeight: 'bold',
      color: theme.colors.primary,
    },
  }),
  loginGoogle: StyleSheet.create({
    forgotPassword: {
      width: '100%',
      alignItems: 'flex-end',
      marginBottom: 24,
    },
    row: {
      flexDirection: 'row',
      marginTop: 4,
    },
    forgot: {
      fontSize: 13,
      color: theme.colors.secondary,
    },
    link: {
      fontWeight: 'bold',
      color: theme.colors.primary,
    },
  }),
  loginWithGFA: StyleSheet.create({
    button: {
      marginTop: 24,
    },
    buttonEnabled: {
      backgroundColor: 'black',
    },
    buttonDisabled: {
      backgroundColor: 'gray',
    },
    row: {
      flexDirection: 'row',
      marginTop: 4,
    },
    link: {
      fontWeight: 'bold',
      color: theme.colors.primary,
    },
  }),
  myRewards: StyleSheet.create({
    safeArea: {
      flex: 1,
    },
    headerContainer: {
      flexDirection: 'row',
      // alignItems: 'center',
      // alignSelf: 'center',
      // justifyContent: 'space-between',
      // textAlign: 'center',
      paddingTop: 10,
      width: '100%',
      backgroundColor: '#FFF',
      zIndex: 1,
    },
    backButton: {
      paddingLeft: '20px',
    },
    headerTitle: {
      // alignSelf: 'center',
      fontWeight: '600',
      fontSize: 16,
      color: '#000',
    },
    listFrame: {
      marginTop: 60,
    },
    rewardItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: '#FFF',
      borderBottomWidth: 1,
      borderColor: '#E0E0E0',
    },
    dateText: {
      fontSize: 16,
      fontWeight: '500',
      color: '#333',
    },
    descriptionText: {
      fontSize: 14,
      color: '#666',
    },
    updateButton: {
      backgroundColor: 'rgba(0,0,0,0.75)',
      borderRadius: 3,
      paddingVertical: 6,
      paddingHorizontal: 12,
    },
    updateButtonText: {
      color: '#FFF',
      fontSize: 14,
    },
  }),
  logo: StyleSheet.create({
    image: {
      width: 139.47,
      height: 139.47,
      marginBottom: 8,
    },
  }),
  paragraph: StyleSheet.create({
    text: {
      fontSize: 15,
      lineHeight: 21,
      textAlign: 'center',
      marginBottom: 12,
    },
  }),
  profileScreen: StyleSheet.create({
    headerContainer: {
      //display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    header: {
      color: theme.colors.greet,
      fontSize: 16,
      fontStyle: 'normal',
      fontWeight: 'bold',
      lineHeight: 22,
      //flex: 1,
      // textAlign: 'left',
      //justifyContent: 'center',
    },
    editButton: {
      borderRadius: 14, // Half of the button's width/height
      borderWidth: 1,
      borderColor: '#000',
      borderStyle: 'solid',
      paddingHorizontal: 16, // Adjust padding as needed
      paddingVertical: 8, // Adjust padding as needed
      width: 30, // Set the width to make it elliptical
      height: 20, // Set the height to make it elliptical
      alignItems: 'center', // Center content horizontally
      justifyContent: 'center', // Center content vertically
    },
    editButtonText: {
      color: theme.colors.greet,
      fontSize: 12,
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: 16,
      textAlign: 'center',
    },
    container: {
      width: '100%',
      marginTop: 50,
    },
    profileHeader: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: '18px',
    },
    profilePic: {
      width: 100,
      height: 100,
      justifyContent: 'center',
      alignItems: 'center',
    },
    userNameContainer: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '8px',
    },
    userName: {
      color: theme.colors.greet,
      fontSize: 22,
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: 'normal',
    },
    ProgressContainer: {
      width: '100%',
      paddingHorizontal: 32,
      paddingVertical: 8,
      flexDirection: 'column',
      alignItems: 'center',
      gap: '8px',
    },
    ProgressTitleContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      gap: '8px',
    },
    ProgressTitle: {
      fontSize: 14,
      color: theme.colors.greet,
      fontStyle: 'normal',
      fontWeight: 400,
      lineHeight: 16,
    },

    progressBarContainer: {
      alignItems: 'center',
      width: '100%',
    },
    progressBar: {
      width: '100%',
      height: 8,
      borderRadius: 50,
      justifyContent: 'center',
      backgroundColor: '#D9D9D9',
    },
    progress: {
      height: '100%',
      backgroundColor: '#13D402',
      borderRadius: 50,
    },
    ProgressTag: {
      flexDirection: 'row',
      width: '100%',
    },
    xpTestContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
    },
    xpTest: {
      fontSize: 12,
      color: '#0A8300',
    },
    xpRemainingContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    xpRemaining: {
      fontSize: 12,
      color: '#B2BEB5',
    },
    statsContainer: {
      alignItems: 'center',

      justifyContent: 'space-around',
      width: '100%',
      paddingVertical: 8,
      paddingHorizontal: 23,
    },
    box: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      paddingBottom: 8,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: 'rgba(0, 0, 0, 0.1)',
      overflow: 'hidden',
    },
    weekContainer: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 18,
      borderRadius: 6,
    },
    daysContainer: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    days: {
      padding: 8,
      marginBottom: 10,
    },
    icon: {
      width: 24,
      height: 24,
    },
    statContainer: {
      width: 300,
      paddingVertical: 16,
      paddingHorizontal: 20,
      paddingBottom: 8,
      flexDirection: 'row',
      alignItems: 'center',
    },

    statBox: {
      display: 'flex',
      height: 74,
      paddingVertical: 8,
      paddingHorizontal: 0,
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: 8,
      flex: 1,
      borderRadius: 8,
      borderWidth: 0.5,
      borderColor: 'rgba(0, 0, 0, 0.10)',
    },
    statRow: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
      gap: '4px',
    },
    statNumber: {
      width: 23,
      height: 28,
      color: '#000',
      fontFamily: theme.colors.greet,
      fontSize: 20,
      fontStyle: 'normal',
      fontWeight: '500',
      lineHeight: 28,
      textOverflow: 'ellipsis',
      overflow: 'hidden',
    },
    statText: {
      color: '#2E2D2D',
      fontFamily: theme.colors.greet,
      fontSize: 10,
      fontStyle: 'normal',
      fontWeight: '300',
      lineHeight: 16,
    },
    button: {
      display: 'flex',
      height: 74,
      paddingVertical: 8,
      paddingHorizontal: 0,
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#F2F2F2',
      borderRadius: 8,
      borderWidth: 0.5,
      borderColor: 'rgba(0, 0, 0, 0.10)',
      marginVertical: 16,
      width: 250,
    },

    buttonText: {
      color: '#2E2D2D',
      fontFamily: theme.colors.greet,
      fontSize: 16,
      fontStyle: 'normal',
      fontWeight: '500',
      lineHeight: 16,
    },
    logout: {
      backgroundColor: 'red',
      borderRadius: '0px',
    },
    logoutText: {
      color: 'white',
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
    },
  }),
  quiz: StyleSheet.create({
    button: {
      backgroundColor: 'black',
    },
    AnswerBox: {
      width: 361,
      height: 214,
      borderWidth: 3,
      borderRadius: 6,
      borderColor: 'rgba(0, 0, 0, 0.05)',
      backgroundColor: 'rgba(0, 0, 0, 0.05)',
      alignItems: 'center',
      justifyContent: 'center',
    },

    answerText: {
      textAlign: 'center',
      fontSize: 24,
    },
    questionContainer: {
      width: '100%',
      paddingHorizontal: 16,

      flex: 1,

      backgroundColor: '#fff',

      paddingVertical: 10,
      flexDirection: 'row',
      alignSelf: 'stretch',
      justifyContent: 'center',
      alignItems: 'center',
    },
    question: {
      fontSize: 18,
      letterSpacing: 0.2,
      lineHeight: 25,
      textAlign: 'left',
      flex: 1,
    },
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    correctBox: {
      borderColor: 'rgba(19, 212, 2, 1)',
    },
    wrongBox: {
      borderColor: 'rgba(241, 58, 0, 1)',
    },
    topProgressBarContainer: {
      width: '100%',
      // height: 20,
      flexDirection: 'row',
      // alignSelf: 'stretch',
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
      paddingVertical: 0,
      gap: 8,
      //flex: 1,
    },
    progressBar: {
      flex: 1,
    },
    x: {
      width: 24,
      height: 24,
      overflow: 'hidden',
    },

    correctMessage: {
      color: 'rgba(98, 218, 103, 1)',
      fontSize: 24,
      textAlign: 'center',
      marginBottom: 30,
    },
    wrongMessage: {
      color: 'rgba(255, 72, 15, 1)',
      fontSize: 24,
      textAlign: 'center',
      marginBottom: 20,
    },
    customMessage: {
      color: 'black',
      fontSize: 16,
      position: 'absolute',
      top: 390,
      width: '100%',
      textAlign: 'left',
    },
    disabledButton: {
      backgroundColor: 'black',
    },
    disabledButtonText: {
      color: 'white',
    },
  }),
  quizEndingScreen: StyleSheet.create({
    frame: {
      justifyContent: 'center',
      alignItems: 'center',
      gap: 24,
    },
    circle: {
      height: 93,
      width: 93,
      zIndex: 0,
    },
    score: {
      fontSize: 26,
      fontWeight: 'bold',
      lineHeight: 22,
      //  textAlign: 'left',
      // zIndex: 1,
    },
    wrapper: {
      //ejustifyContent: 'center',
      // alignItems: 'center',
      marginBottom: 324.88,
    },

    lightning: {
      position: 'absolute',
      top: 23,
      //left: 23,
      width: 48,
      height: 48,
      //overflow: "hidden",
      //zIndex: 2,
    },
    button: {
      backgroundColor: '#62DA67',

      /* borderRadius: 8,
      width: 336,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginLeft: -168,
      bottom: 32,
      left: '50%',
      position: 'absolute',*/
    },
    text: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 80,
      alignItems: 'center',
      textAlign: 'center',
    },
  }),
  quizStreakScreen: StyleSheet.create({
    button: {
      backgroundColor: 'black',
    },
    userInfoContainer: {
      flexDirection: 'column',
      alignItems: 'center',
      marginBottom: 16,
    },
    header: {
      fontWeight: 'bold',
      fontSize: 22,
    },
    lightningContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: 362.24,
    },
    lightningDayContainer: {
      alignItems: 'center',
      marginHorizontal: 5,
    },
    lightningIcon: {
      marginRight: 5,
    },
    dayText: {
      color: 'black',
      fontSize: 16,
      fontWeight: 'bold',
      marginTop: 5,
    },
  }),
  redoQuestionsScreen: {
    button: {
      backgroundColor: 'black',
    },
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    text: {
      fontSize: 17,
      fontWeight: 'bold',
      marginBottom: 300,
      textAlign: 'left',
      marginTop: -260,
    },

    progressBarContainer: {
      width: '100%',
      height: 20,
      marginBottom: 300,
    },
  },
  registerScreen: {
    row: {
      flexDirection: 'row',
      marginTop: 4,
    },
    link: {
      fontWeight: 'bold',
      color: theme.colors.primary,
    },
  },
  signIn: StyleSheet.create({
    button: {
      backgroundColor: 'black',
      marginTop: 24,
    },
    row: {
      flexDirection: 'row',
      marginTop: 4,
    },
    top: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
      paddingVertical: 16,
      position: 'relative',
    },
    backButton: {
      position: 'absolute',
      left: 16,
    },
    link: {
      fontWeight: 'bold',
      color: theme.colors.primary,
    },
  }),
  signUpForm: StyleSheet.create({
    container: {
      flex: 1,
      padding: 16,
      backgroundColor: 'white',
    },
    header: {
      fontSize: 24,
      marginBottom: 24,
    },
    input: {
      borderWidth: 1,
      borderColor: '#ccc',
      padding: 8,
      marginVertical: 8,
      borderRadius: 4,
    },
    checkboxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 16,
    },
    checkboxLabel: {
      marginLeft: 8,
    },
  }),
  startScreen: StyleSheet.create({
    title: {
      fontSize: 54,
      lineHeight: 20,
      fontWeight: '500',
    },
    separatorContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 20,
      width: '100%',
    },
    line: {
      flex: 1,
      height: 1,
      backgroundColor: 'black',
    },
    orText: {
      marginHorizontal: 10,
      color: 'gray',
    },
    buttonBorder: {
      borderColor: 'black',
      borderWidth: 1,
      borderRadius: 8,
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 5,
    },
    iconStyle: {
      marginRight: 10,
    },
    buttonText: {
      flex: 1,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: 'bold',
      color: 'black',
    },
    continueButton: {
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 20,
      marginVertical: 10,
    },
    continueButtonEnabled: {
      backgroundColor: 'black',
    },
    continueButtonDisabled: {
      backgroundColor: 'gray',
    },
    continueButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    googleButton: {
      backgroundColor: '#ffffff',
    },
    facebookButton: {
      backgroundColor: '#ffffff',
    },
    appleButton: {
      backgroundColor: '#ffffff',
    },
    // Ensure the button styles apply to all states
    button: {
      backgroundColor: 'black', // Add this line to apply background color
    },
    header: {
      textAlign: 'center',
      alignItems: 'center',
    },
  }),
  takeActionScreen: StyleSheet.create({
    container: {
      flex: 1,
      padding: 20,
      backgroundColor: '#FFF',
    },
    headerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      position: 'relative',
    },
    backButton: {
      position: 'absolute',
      left: 0,
    },
    header: {
      fontSize: 16,
      color: theme.colors.greet,
      fontWeight: 500,
      lineHeight: 22,
    },
    subHeader: {
      fontSize: 18,
      fontWeight: 500,
      lineHeight: 22,
      marginBottom: 10,
    },
    description: {
      fontSize: 16,
      fontWeight: 400,
      lineHeight: 22,
      letterSpacing: 0.16,
      marginBottom: 20,
    },
    funFactContainer: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      borderWidth: 1,
      borderColor: '#ccc',
      paddingVertical: 8,
      paddingHorizontal: 16,
      marginBottom: 20,
      borderRadius: 5,
      backgroundColor: '#F0F0F0',
    },
    iconContainer: {
      position: 'relative',
      width: 50,
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      borderradius: 27,
      gap: 16,
      bottom: 2,
    },
    Circle: {
      width: '100%',
      height: '100%',
      resizeMode: 'contain',
    },
    BulbIcon: {
      position: 'absolute',
      width: '50%',
      height: '50%',
      resizeMode: 'contain',
    },
    funFactText: {
      fontSize: 16,
      fontWeight: 400,
      lineHeight: 19,
      marginLeft: 16,
      flexShrink: 1,
    },
    unplugText: {
      color: '#000',
      fontSize: 16,
      fontWeight: 600,
      lineHeight: 19,
      marginBottom: 20,
    },
    checkboxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
      gap: 14,
    },
    checkbox: {
      width: 16,
      height: 16,
      borderWidth: 2,
      borderColor: '#000',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
    },
    checkIcon: {
      width: 16,
      height: 16,
    },
    checkboxLabel: {
      fontSize: 16,
      fontWeight: 400,
      lineHeight: 19,
    },
    photoLabel: {
      fontSize: 16,
      marginBottom: 10,
      fontWeight: 'bold',
    },
    photoContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
    },
    photoWrapper: {
      position: 'relative',
      margin: 5,
    },
    photo: {
      width: 50,
      height: 50,
      borderRadius: 5,
    },
    deleteButton: {
      position: 'absolute',
      top: 2,
      right: 2,
      backgroundColor: '#888',
      borderRadius: 8,
      padding: 2,
    },
    uploadButton: {
      width: 50,
      height: 50,
      borderWidth: 1,
      borderColor: '#ccc',
      justifyContent: 'center',
      alignItems: 'center',
      margin: 5,
      borderRadius: 5,
      backgroundColor: '#F0F0F0',
    },
    completeButton: {
      marginTop: 20,
      padding: 15,
      borderRadius: 5,
      alignItems: 'center',
    },
    completeButtonText: {
      color: '#fff',
      fontSize: 16,
    },
  }),
  textInput: StyleSheet.create({
    container: {
      width: '100%',
      marginVertical: 7,
    },
    input: {
      backgroundColor: theme.colors.surface,
    },
    description: {
      fontSize: 13,
      color: theme.colors.secondary,
      paddingTop: 8,
    },
    error: {
      fontSize: 13,
      color: theme.colors.error,
      paddingTop: 8,
    },
    title: {
      fontFamily: 'Poppins',
      fontSize: 14,
      marginTop: 4,
      marginBottom: 2,
      color: 'black',
      fontWeight: '500',
      lineHeight: 20,
      letterSpacing: 0,
      textAlign: 'left',
      fontStyle: 'normal',
    },
  }),
  triviaToActionConnect: StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      backgroundColor: '#fff',
    },
    content: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      marginTop: '50px',
    },
    card: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#ccc',
      backgroundColor: '#f7f7f7',
      marginBottom: 20,
      width: '90%',
    },
    celebrate: {
      width: 80,
      height: 80,
      resizeMode: 'contain',
      marginBottom: 10,
    },
    coinsText: {
      fontSize: 25,
      fontWeight: 'bold',
      // marginVertical: 10,
    },
    messageText: {
      fontSize: 18,
      marginTop: 10,
    },
    doneButton: {
      padding: 15,
      backgroundColor: '#000',
      borderRadius: 5,
      alignItems: 'center',
      width: '100%',
      marginBottom: 30,
    },
    doneButtonText: {
      color: '#fff',
      fontSize: 16,
    },
  }),
  welcomeScreen: StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'white', // Set background color to white
    },
    image: {
      width: 300,
      height: 500,
      resizeMode: 'contain',
      filter: 'grayscale(100%)', // Apply grayscale effect
    },
    text: {
      marginTop: 10, // Adjust the margin as needed
      fontSize: 40, // Adjust the font size as needed
      fontWeight: 'bold', // Make the text bold
      color: 'black', // Text color
      textAlign: 'center', // Center align the text
    },
  }),
}

export default styles
